pipeline {
    agent {
        // Use a Docker image with Maven pre-installed
        docker { 
            image 'maven:3.8.4'
            args '-v $HOME/.m2:/root/.m2' // Mount Maven local repository for caching dependencies
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Compile Java code using Maven
                    sh 'mvn clean install'
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    // Run the Java application
                    sh 'java -cp target/classes HelloWorld'
                }
            }
        }
    }

    post {
        always {
            // Clean up: delete Maven artifacts
            deleteDir()
        }
    }
}
